dist: xenial

language: python
python:
  - "3.8"

notifications:
  email:
    - powen@renci.org

before_install:
  - git pull
  - git clone https://github.com/ObesityHub/robokop-genetics.git

# command to install dependencies
install:
  - pip install -r requirements.txt

env:
  global:
    - PYTHONPATH=$PWD:$PWD/robokop-genetics
    - ROBOKOP_HOME=$PWD

# command to run tests
script:
  - mkdir logs
#  - ls -al
#  - echo $PYTHONPATH
#  - echo $ROBOKOP_HOME
  - pytest -p no:warnings tests

after_success:
  - coveralls
