dist: xenial

language: python
python:
  - "3.8.5"

notifications:
  email:
    - powen@renci.org
    - evandietzmorris@gmail.com

before_install:
  - git pull
  - git clone https://github.com/ObesityHub/robokop-genetics.git

# command to install dependencies
install:
  - pip install -r requirements.txt

env:
  global:
    - PYTHONPATH=$PWD:$PWD/robokop-genetics
    - ROBOKOP_HOME=$PWD
    - DATA_SERVICES_LOGS=$PWD/logs
    - DATA_SERVICES_STORAGE=tests/storage

# command to run tests
script:
  - mkdir logs
  - mkdir tests/storage
#  - ls -al
#  - echo $PYTHONPATH
#  - echo $ROBOKOP_HOME
  - pytest -p no:warnings tests

after_success:
  - coveralls