dist: xenial

language: python
python:
  - "3.8"

notifications:
  email:
    - powen@renci.org

before_install:
  - git pull
  - git clone https://github.com/ObesityHub/robokop-genetics.git
  - git clone https://github.com/TranslatorIIPrototypes/robo-commons.git

# command to install dependencies
install:
  - pip install -r requirements.txt

env:
  global:
    - PYTHONPATH=$PWD:$PWD/robokop-genetics:$PWD/robo-commons

# command to run tests
script:
  - ls -al
  - mkdir logs
  - pytest -p no:warnings tests

after_success:
  - coveralls
