version: "3.7"
services:
  data_services:
    build:
      context: .
    environment:
      - DATA_SERVICES_STORAGE=/Data_services_storage
      - DATA_SERVICES_GRAPHS=/Data_services_graphs
      - DATA_SERVICES_GRAPH_SPEC
      - DATA_SERVICES_LOGS=/Data_services_logs
      - "HOST_STORAGE_DIR=${DATA_SERVICES_STORAGE}"
    volumes:
      - .:/Data_services
      - "${DATA_SERVICES_STORAGE}:/Data_services_storage"
      - "${DATA_SERVICES_GRAPHS}:/Data_services_graphs"
      - "${DATA_SERVICES_LOGS}:/Data_services_logs"
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - ds_network

networks:
  ds_network:
    name: data_services_network
