version: "3.8"
services:
  data_services:
    build:
      context: .
    environment:
      - DATA_SERVICES_STORAGE=/Data_services_storage
      - DATA_SERVICES_LOGS=/Data_services_logs
      # this passes the DATA_SERVICES_CONFIG environment variable from the host straight to the container
      # DATA_SERVICES_CONFIG is expected to be a file name for a config file in the storage directory
      - DATA_SERVICES_CONFIG
      - DATA_SERVICES_TEST_MODE
    volumes:
      - .:/Data_services
      - "${DATA_SERVICES_STORAGE}:/Data_services_storage"
      - "${DATA_SERVICES_LOGS}:/Data_services_logs"
