apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ds-graphs-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.dataServices.graphsVolume.size }}
  storageClassName: basic