{{- if not .Values.dataServices.sourcesVolume.use_nfs }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ds-sources-pvc
  annotations:
    "helm.sh/resource-policy": keep
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.dataServices.sourcesVolume.size }}
    limits:
      storage: {{ .Values.dataServices.sourcesVolume.size }}
  storageClassName: basic
{{- end }}