# Default values for kgx-load-helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1


kgx:
  image:
    repository: renciorg/dataservices
    pullPolicy: Always
    tag: "kgx-test"
  storage:
   size: 10Gi
  files:
    baseUrl: https://stars.renci.org/var/kgx_data/v3.0/
    node: Biolink_nodes_v3.0.jsonl
    edge: Biolink_edges_v3.0.jsonl
  resources: {}
  init:
    resources:
     requests:
       memory: 2Gi
       cpu: 500m
     limits:
       memory: 2Gi
       cpu: 500m

neo4j:
  image:
    repository: renciorg/neo4j-4.2.14-apoc-gds
    tag: 0.0.1
    imagePullPolicy: Always

  service:
    type: ClusterIP
  httpPort: 7474
  boltPort: 7687
  password: neo4jkp
  username: neo4j
  # These are jvm based values hence suffix with one of the following G, M etc...
  heapSize: 8G
  pageCacheSize: 4G
  # It's used to request the cluster for memory capable of running neo4j per the heap and PageCache values above
  # Compute this value by summing up heapSize + pageCacheSize + (1G for os)
  # https://neo4j.com/docs/operations-manual/current/performance/memory-configuration/
  totalMemory: 14G
  storage:
    size: 10Gi
  resources:
    requests:
      memory: 14Gi
    limits:
      memory: 14Gi
      cpu: 1500m


  # Readiness probes will send a kill signal to the container if
  # it fails enough times.  It's therefore very important
  # that initialDelaySeconds give the cluster time to form, because
  # if readiness probes start immediately after container start,
  # they may end up not forming quickly enough and getting killed.
  readinessProbe:
    initialDelaySeconds: 30
    failureThreshold: 3
    timeoutSeconds: 10
    periodSeconds: 10
    exec:
      command:
        - bash
        - -c
        - IFS="/" read -a auth <<< $NEO4J_AUTH ; cypher-shell -u ${auth[0]} -p ${auth[1]} "match (c) return c limit 1"

  livenessProbe:
    initialDelaySeconds: 60
    periodSeconds: 10
    failureThreshold: 3
    timeoutSeconds: 10
    exec:
      command:
        - bash
        - -c
        - IFS="/" read -a auth <<< $NEO4J_AUTH ; cypher-shell -u ${auth[0]} -p ${auth[1]} "match (c) return c limit 1"

  # Startup probes are used to know when a container application has started.
  # If such a probe is configured, it disables liveness and readiness checks until it succeeds
  startupProbe:
    failureThreshold: 2000
    periodSeconds: 1
    timeoutSeconds: 10
    exec:
      command:
        - bash
        - -c
        - IFS="/" read -a auth <<< $NEO4J_AUTH ; cypher-shell -u ${auth[0]} -p ${auth[1]} "match (c) return c limit 1"