# Values for running data-services on Sterling at RENCI

replicaCount: 1

dataServices:
  graphID: "HGNC_Automat"
  graphSpec: "default-graph-spec.yml"
  # useLocalGraphSpec true if the graphSpec is a file in the codebase (mainly for testing), false if a remote URL
  useLocalGraphSpec: true
  buildMode: true
  image:
    repository: evandietzmorris/data_services
    pullPolicy: Always
    tag: latest
  graphsVolume:
    use_nfs: true
    nfs_server: na-projects.edc.renci.org
    nfs_path: /stars/Data_services
    nfs_mount_subpath: biolink3/graphs/
  sourcesVolume:
    use_nfs: true
    nfs_server: na-projects.edc.renci.org
    nfs_path: /stars/Data_services
    nfs_mount_subpath: biolink3/storage/
  neo4jScratchVolume:
    size: 80Gi
  resources:
    limits:
      cpu: "2"
      memory: 38Gi
      ephemeral-storage: 2Gi
    requests:
      cpu: "2"
      memory: 32Gi
      ephemeral-storage: 1Gi
  httpsProxy:
    useProxy: true
    proxyURL: http://proxy.renci.org:8080/
  securityContext:
    runAsUser: 30000
    runAsGroup: 1000
  normalization:
    nodeNormEndpoint: 
    edgeNormEndpoint:
