# Values for running data-services on Sterling at RENCI

replicaCount: 1

dataServices:
  graphID: "Test_Graph"
  graphSpec: "testing-graph-spec.yml"
  remoteSyncDirectory: 'realuser@realserver.org:/path/to/graphs_directory'
  image:
    repository: evandietzmorris/data_services
    pullPolicy: IfNotPresent
    tag: latest
  graphsVolume:
    size: 120Gi
  sourcesVolume:
    size: 120Gi
  resources:
    limits:
      cpu: "4"
      memory: 28Gi
    requests:
      cpu: "4"
      memory: 28Gi
  httpProxy:
    useProxy: true
    proxyURL: http://proxy.renci.org:8080/

neo4j:
  image:
    repository: neo4j
    pullPolicy: IfNotPresent
    tag: 4.3
  username: neo4j
  password: neo4jpw
  resources:
    limits:
      cpu: "4"
      memory: 28Gi
    requests:
      cpu: "4"
      memory: 28Gi