# Default values for data-services.

replicaCount: 1

dataServices:
  graphID: "Test_Graph"
  graphSpec: "testing-graph-spec.yml"
  # useLocalGraphSpec true if the graphSpec is a file in the codebase (mainly for testing), false if a remote URL
  useLocalGraphSpec: true
  buildMode: true
  image:
    repository: evandietzmorris/data_services
    pullPolicy: IfNotPresent
    tag: latest
  graphsVolume:
    use_nfs: false
    nfs_server:
    nfs_path:
    nfs_mount_subpath:
    size: 32Gi # if use_nfs is set to true size is ignored
  sourcesVolume:
    use_nfs: false
    nfs_server:
    nfs_path:
    nfs_mount_subpath:
    size: 32Gi # if use_nfs is set to true size is ignored
  neo4jScratchVolume:
    size: 16Gi # if use_nfs is set to true size is ignored
  resources:
    limits:
      cpu: "1"
      memory: 16Gi
      ephemeral-storage: 2Gi
    requests:
      cpu: "1"
      memory: 16Gi
      ephemeral-storage: 1Gi
  httpsProxy:
    useProxy: false
    proxyURL:
  securityContext:
    runAsUser:
    runAsGroup:
  normalization:
    nodeNormEndpoint:
    edgeNormEndpoint:
