apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "kgx-load-helm.fullname" . }}-neo4j
  labels:
    {{- include "plater.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "kgx-load-helm.fullname" . }}-neo4j-service
  selector:
    matchLabels:
      {{- include "plater.selectorLabels" . | nindent 6 }}
      service-type: database
  template:
    metadata:
      labels:
        {{- include "plater.selectorLabels" . | nindent 8 }}
        service-type: database
    spec:
      containers:
        - image: {{ .Values.image.neo4j.repository }}:{{ .Values.image.neo4j.tag }}
          name: {{ include "kgx-load-helm.fullname" . }}-neo4j-container
          {{- with .Values.app.neo4j.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          imagePullPolicy:  {{ .Values.image.neo4j.imagePullPolicy }}
          env:
          - name: NEO4J_AUTH
            value: {{ .Values.app.neo4j.username }}/{{ .Values.app.neo4j.password }}
          - name: NEO4J_dbms_connectors_default__listen__address
            value: "0.0.0.0"
          - name: NEO4J_dbms_memory_heap_initial__size
            value: "{{ .Values.app.neo4j.heapSize }}"
          - name: NEO4J_dbms_memory_heap_max__size
            value: "{{ .Values.app.neo4j.heapSize }}"
          - name: NEO4J_dbms_memory_pagecache_size
            value: "{{ .Values.app.neo4j.pageCacheSize }}"
          - name: NEO4J_dbms_read__only
            value: {{ .Values.app.neo4j.readOnly }}
          - name: NEO4J_dbms_security_procedures_unrestricted
            value: "apoc.*"
          - name: NEO4J_dbms_jvm_additional
            value: "-XX:+UnlockExperimentalVMOptions -XX:+UseZGC -Xss{{ .Values.app.neo4j.jvmStackSize }} -Dlog4j2.disable.jmx=true -Dlog4j2.formatMsgNoLookups=true"
          - name: NEO4J_dbms_transaction_timeout
            value: "{{ .Values.app.Neo4jQueryTimeout }}s"
          ports:
            - name: neo4j-http
              containerPort: 7474
              protocol: TCP
            - name: neo4j-https
              containerPort: 7473
              protocol: TCP
            - name: neo4j-bolt
              containerPort: 7687
              protocol: TCP
          volumeMounts:
          - mountPath: /data
            name: {{ include "kgx-load-helm.fullname" . }}-neo4jkp-pvc
            subPath: neo4j_data
          - mountPath: /logs
            name: {{ include "kgx-load-helm.fullname" . }}-neo4jkp-pvc
            subPath: neo4j_logs
          startupProbe:
{{ toYaml .Values.neo4j.startupProbe | indent 12 }}
          readinessProbe:
{{ toYaml .Values.neo4j.readinessProbe | indent 12 }}
          livenessProbe:
{{ toYaml .Values.neo4j.livenessProbe | indent 12 }}
      restartPolicy: Always
    {{ with .Values.neo4j.affinity }}
      affinity:
        {{ toYaml . | nindent 8 }}
    {{ end }}
    {{ with .Values.neo4j.tolerations }}
      tolerations:
      {{ toYaml . | nindent 8 }}
    {{ end }}
      volumes:
        - name: {{ include "kgx-load-helm.fullname" . }}-scripts
          configMap:
            name: {{ include "kgx-load-helm.fullname" . }}-configmap
            defaultMode: 0777
  volumeClaimTemplates:
    - metadata:
        name: {{ include "kgx-load-helm.fullname" . }}-neo4jkp-pvc
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.app.neo4j.storage.size }}
