apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{- include "kgx-load-helm.fullname" . }}-scripts"
data:
  download-kgx-files.sh: |-
    #!/bin/sh -x
    export DATA_DIR=/data
    node_file_url={{ .Values.kgx.files.baseUrl }}{{ .Values.kgx.files.node }}
    edge_file_url={{ .Values.kgx.files.baseUrl }}{{ .Values.kgx.files.edge }}
    wget  -O /data/nodes.jsonl $node_file_url
    wget -O /data/edges.jsonl $edge_file_url
    cd $DATA_DIR
    ls -al $DATA_DIR
    echo "FINISHED"

  check_neo.sh: |-
    #!/bin/sh
    response=$(wget --server-response --spider --quiet "http://${NEO4J_HOST}:${NEO4J_HTTP_PORT}" 2>&1 | awk 'NR==1{print $2}')
    until [ "$response" = "200" ]; do
        response=$(wget --server-response --spider --quiet "http://${NEO4J_HOST}:${NEO4J_HTTP_PORT}" 2>&1 | awk 'NR==1{print $2}') >&2
        echo "  -- Neo4j  is unavailable - sleeping" $response
        sleep 3
    done