###############
# test workflow for Data_services
# powen, 8/11/2021
###############

name: 'test'

on: [push]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
    steps:
      - name: create env params
        run: |
          echo "PYTHONPATH=$PWD:$PWD/robokop-genetics" >> $GITHUB_ENV
          echo "ROBOKOP_HOME=$PWD" >> $GITHUB_ENV
          mkdir -p $PWD/logs
          mkdir -p $PWD/storage
          echo "DATA_SERVICES_LOGS=$PWD/logs" >> $GITHUB_ENV
          echo "DATA_SERVICES_STORAGE=$PWD/storage" >> $GITHUB_ENV
          ls $PWD

      - name: display env params
        run: echo "${{env.PYTHONPATH}}, ${{ env.ROBOKOP_HOME }}, ${{ env.DATA_SERVICES_LOGS }}, ${{ env.DATA_SERVICES_STORAGE }}"

      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run pytest
        run: |
          python -m pytest tests/
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
          env_vars: OS,PYTHON