###############
# test workflow for Data_services
# powen, 8/11/2021
###############

name: 'test'

on: [push]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: $GITHUB_WORKSPACE:$GITHUB_WORKSPACE/robokop-genetics
      ROBOKOP_HOME: $GITHUB_WORKSPACE
      DATA_SERVICES_LOGS: "tests/logs"
      DATA_SERVICES_STORAGE: "tests/storage"
    strategy:
      matrix:
        python-version: [3.9]
    steps:
      - name: display env params
        run: echo "$PYTHONPATH, $ROBOKOP_HOME, $DATA_SERVICES_LOGS, $DATA_SERVICES_STORAGE"

      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run pytest
        run: |
          python -m pytest --cov=binder --cov-report=xml tests/
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
          env_vars: OS,PYTHON